# =====================================================================
# CERTIFICATION SCENARIO 137: MULTI-ACCOUNT GOVERNANCE ANALYTICS MESH
# COMPONENT: ATHENA SQL ENGINE SCHEMAS MAPPING AWS CONFIG EXPORTS
# =====================================================================

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = "us-east-1" # Deployed inside your Central Master Security/Log-Archive Account
}

# 1. Reference Your Centralized Multi-Account Compliance S3 Storage Bucket Vault
# (This acts as the master landing pad where cross-account Config snapshots stream in)
data "aws_s3_bucket" "central_compliance_vault" {
  name = "enterprise-multicloud-ssm-inventory-sync-2026" # Reuses your existing Scenario 43 secure vault!
}

# 2. Deploy the Core Governance Delivery Channel Streaming Configurations
# (Deploys inside child environments to stream real-time snapshot files to the hub)
resource "aws_config_delivery_channel" "compliance_stream" {
  name           = "enterprise-global-compliance-stream"
  s3_bucket_name = data.aws_s3_bucket.central_compliance_vault.id
  s3_key_prefix  = "aws-config-snapshots"

  snapshot_delivery_properties {
    delivery_frequency = "TwentyFour_Hours" # Stream complete compliance logs daily
  }
}

# 3. Provision the Serverless Athena Compliance Database Core Frame
resource "aws_athena_database" "compliance_audit_db" {
  name   = "enterprise_config_compliance_audit_db"
  bucket = data.aws_s3_bucket.central_compliance_vault.bucket # Primary query workspace bucket destination
}

# 4. Architect the Athena Table Creation Schema Query Definition
# This structural block writes out the DDL statement needed to parse and index
# the highly complex nested JSON structures generated by multi-account AWS Config snapshots.
resource "aws_athena_named_query" "create_config_table_schema" {
  name        = "CreateAWSConfigSnapshotTableSchema"
  database    = aws_athena_database.compliance_audit_db.name
  description = "Deploys a structured column schema mapping over aggregated cross-account compliance logs"

  query = <<EOF
CREATE EXTERNAL TABLE IF NOT EXISTS ${aws_athena_database.compliance_audit_db.name}.aws_config_configuration_snapshot (
    fileversion STRING,
    configSnapshotId STRING,
    configurationItems ARRAY<STRUCT<
        configurationItemVersion STRING,
        configurationItemCaptureTime STRING,
        configurationItemStatus STRING,
        configurationStateId STRING,
        accountId STRING,
        awsRegion STRING,
        availabilityZone STRING,
        resourceType STRING,
        resourceId STRING,
        resourceName STRING,
        arn STRING,
        complianceType STRING
    >>
)
ROW FORMAT SERDE 'org.openx.data.jsonserde.JsonSerDe'
LOCATION 's3://${data.aws_s3_bucket.central_compliance_vault.bucket}/aws-config-snapshots/';
EOF
}

# 5. Pre-Save an Incident Response Query to Instantly Isolate Cross-Account Non-Compliant Breaks
resource "aws_athena_named_query" "query_non_compliant_resources" {
  name        = "ForensicSearchNonCompliantAssets"
  database    = aws_athena_database.compliance_audit_db.name
  description = "Queries the aggregated database to pinpoint the exact account and region of failed resources"

  query = <<EOF
SELECT 
    item.accountId, 
    item.awsRegion, 
    item.resourceType, 
    item.resourceId, 
    item.resourceName,
    item.complianceType
FROM ${aws_athena_database.compliance_audit_db.name}.aws_config_configuration_snapshot
CROSS JOIN UNNEST(configurationItems) AS t(item)
WHERE item.complianceType = 'NON_COMPLIANT'
ORDER BY item.configurationItemCaptureTime DESC
LIMIT 100;
EOF
}
